[project]
name = "website"
version = "2.0.0"
description = "My World Wide Web page, static site, work catalog."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jinja2>=3.1.6",
    "watchdog>=6.0.0",
]
